bot:
    build: .
    restart: always
    volumes:
        - '/var/log:/var/log'
        - '/mnt/kaz:/mnt/kaz'
    environment:
        - DISCORD_BOTKEY=${DISCORD_BOTKEY}
        - TWITCH_APIKEY=${TWITCH_APIKEY}
        - TWITCH_AUTHKEY=${TWITCH_AUTHKEY}
